# Example configuration for VMServiceScrape
# This file demonstrates how to configure VMServiceScrape for VictoriaMetrics

# VMServiceScrape configuration
vmServiceScrapes:
  app-vms:
    endpoints:
    - interval: 30s
      port: exporter
      path: /metrics
      # Additional VMServiceScrape specific options
      # scrapeTimeout: 10s
      # honorLabels: true
      # honorTimestamps: true
      # metricRelabelings:
      # - sourceLabels: [__name__]
      #   regex: 'node_(.+)'
      #   targetLabel: node_metric
      #   replacement: '${1}'
    extraSelectorLabels:
      app: nginx
    labels:
      foo: foo
      # VMServiceScrape specific labels
      # vm_service_scrape: "true"
    # VMServiceScrape specific parameters
    sampleLimit: 1000  # Maximum number of samples to scrape per target
    streamParse: true  # Enable streaming parsing for better performance

# You can also use the alternative key name (lowercase)
vmservicescrapes:
  app-vms-alt:
    endpoints:
    - interval: 15s
      port: metrics
      path: /metrics
      # VMServiceScrape supports additional features compared to ServiceMonitor
      # - scrapeTimeout: 10s
      # - honorLabels: true
      # - honorTimestamps: true
      # - followRedirects: true
      # - enableHttp2: true
      # - tlsConfig:
      #     insecureSkipVerify: true
      # - basicAuth:
      #     username:
      #       name: basic-auth
      #       key: username
      #     password:
      #       name: basic-auth
      #       key: password
    extraSelectorLabels:
      app: myapp
    labels:
      vm_service_scrape: "true" 